name: terraform

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform init -reconfigure

      - name: Terraform Plan (PR)
        if: github.event_name == 'pull_request'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform plan \
            -lock-timeout=2m \
            -var="project_id=laborinsight-data" \
            -var="gcp_credentials=$GOOGLE_CREDENTIALS"

      - name: Terraform Apply (main)
        if: github.ref == 'refs/heads/main'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          terraform apply -auto-approve \
            -lock-timeout=2m \
            -var="project_id=laborinsight-data" \
            -var="gcp_credentials=$GOOGLE_CREDENTIALS"
